name: Auto Post Telegram News

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Save seen.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [ -f seen.json ]; then
            git add seen.json
            git commit -m "update seen.json" || echo "No changes to commit"
            git push
          else
            echo "seen.json not found, skip commit"
          fi
